version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.34
    environment:
      PRISMA_CONFIG: /app/prisma.yml
    volumes:
      - ./prisma:/app
    ports:
      - '4466:4466'
    depends_on:
      - postgres

volumes:
  postgres-data:
